title_name = "nx1"
title_id = "4156089E"
hash = "A49321A07235881F" # 2-nx1mp.exe

[[patch]]
	name = "stub MAssertVargs"
	author = "and799"
	is_enabled = true

	[[patch.be32]]
		address = 0x82527570
		value = 0x4E800020
