title_name = "nx1"
title_id = "4156089E"
hash = "3C876080C1FFB9AB" # 1-nx1sp.exe

[[patch]]
	name = "stub MAssertVargs"
	author = "and799"
	is_enabled = true

	[[patch.be32]]
		address = 0x824BCD10
		value = 0x4E800020
